.TH TICTAC 1 "January 2025" "1.0" "TicTac Manual"
.SH NAME
paranoid \- Free and open source Tic Tac Toe game made in C
.SH SYNOPSIS
.B tictac 
.B tictac\-clear \- More clear version of TicTac
.SH DESCRIPTION
.B tictac
is a terminal Tic Tac Toe game made in C.

The game is simple: You have a table and you are playing against a bot.
Your goal is to win. If you win, the game exits.

This game is simple and fun. tictac is open source, and free.
.SH GITHUB
https://github.com/AronasGITHUB/tictac.git
.SH FILES
.B /bin/tictac /usr/bin/tictac /usr/local/bin/tictac
The main TicTac file. 

.B /bin/tictac-clear /usr/bin/tictac-clear /usr/local/bin/tictac-clear
A much clear version of Titac. the screen is just cleared and tictac executes. 

.B /usr/share/man/man1/tictac.1
This manual page. 

.B LICENSE
If you got this from a git repository, LICENSE is the license file.

.B .gitignore
If you got this from a git repository, .gitignore is the files to Git to ignore.

.B README.md
If you got this from a git repository, README.md is the instructions.

.B Makefile
If you got this from a git repository, Makefile is the installer.

.SH SEE ALSO
.B 2048
(1)
.SH AUTHOR
Written by AronasGithub.
.SH LICENSE
This game is licensed under The Unlicense.
